export const tableData = [
  {
    id: 1077620,
    shippify: 17713,
    date: "22 jan 2020",
    status: "pending",
    customer: "Ahmed",
    email: "ahmed.123@gmail.com",
    country: "Ausralia",
    shipping: "Australian post",
    source: "Shopify AU",
    ordertype: "Customer",
  },
  {
    id: 1077621,
    shippify: 17713,
    date: "22 jan 2020",
    status: "pending",
    customer: "Ahmed",
    email: "ahmed.123@gmail.com",
    country: "Ausralia",
    shipping: "Australian post",
    source: "Shopify AU",
    ordertype: "Customer",
  },
  {
    id: 1077623,
    shippify: 17713,
    date: "22 jan 2020",
    status: "pending",
    customer: "Ahmed",
    email: "ahmed.123@gmail.com",
    country: "Ausralia",
    shipping: "Australian post",
    source: "Shopify AU",
    ordertype: "Customer",
  },
  {
    id: 1077624,
    shippify: 17713,
    date: "22 jan 2020",
    status: "pending",
    customer: "Ahmed",
    email: "ahmed.123@gmail.com",
    country: "Ausralia",
    shipping: "Australian post",
    source: "Shopify AU",
    ordertype: "Customer",
  },
];
